player_not_found: "\u00A74Spieler %s nicht gefunden!"
chunks:
    regenerate:
        error: "[%s] Regeneration fehlgeschlagen in Chunk X: %d Z: %d!"
        success: "[%s] %d Chunks regeneriert."
plot:
    price_default: 20
    forbidden:
        break: "\u00A74Aua, das tut weh. Lass das!"
        build: "\u00A74Bau wo anders!"
        pvp:
            attacker: "\u00A74Schützt den König!"
            affected: "\u00A7eKein \u00A76PvP \u00A7eauf Grundstücken."
    region:
        wilderness: "\u00A74Du bist in der Wildnis. \u00A7cDiese wird regelmässig gelöscht!"
        plot: "\u00A7eDu bist auf deinem Grundstück. \u00A76Dein Bauwerk ist gesichert."
lock:
    chest:
        owner: "\u00A74Private Kiste von \u00A7c%s\u00A74!"
        locked: "\u00A7aDie Kiste ist gesichert."
        unlocked: "\u00A7aDie Kiste wurde entsichert."
    door:
        owner: "\u00A74Privater Bereich von \u00A7c%s\u00A74!"
        locked: "\u00A7aDie Tür ist gesichert."
        unlocked: "\u00A7aDie Tür wurde entsichert."
command:
    plot:
        release:
            success: "\u00A7aGrundstück ist freigegeben."
            error: "\u00A74Grundstück konnte nicht freigegeben werden!"
    bank:
        transfer: "\u00A72%d Goldbarren \u00A7awurden an den Spieler \u00A72%s \u00A7aüberwiesen."
        balance: "\u00A7aKontostand: \u00A72%d Goldbarren"
    warp:
        set:
            success: "\u00A7aDer Warp \u00A72%s \u00A7awurde erstellt."
            error: "\u00A74Der Warp \u00A7c%s \u00A74kann hier nicht erstellt werden!"
        remove:
            success: "\u00A7aDer Warp \u00A72%s \u00A7awurde entfernt."
            error: "\u00A74Der Warp \u00A7c%s \u00A74konnte nicht entfernt werden!"
stats:
    number: 3
    headline: "\u00A76***** Die reichsten %d Spieler *****"
    row: "\u00A76%s - \u00A7e%d Goldbarren"
    footer: "\u00A76**********************************"
    empty: "\u00A7eWerde der reichste Spieler, \ndurch Goldbarren und Grundstücke."
    info: "[%s] Created player stats"
join:
    normally: "\u00A7e %s is in the House!"
    inventory_full: "\u00A74In deinem Inventar ist kein Platz mehr für Goldbarren!"
    money: "\u00A7eDu hast \u00A76%d Goldbarren \u00A7evon der Bank bekommen."
mainmenu:
    open_with_item: STICK
    menu_title: Spieler Menü
    items:
        plot_buy:
            material: GRASS
            name: Grundstück kaufen
            description:
            - "Besitzer: %s"
            - "Preis: %d Goldbarren"
        plot_sell:
            material: GOLD_INGOT
            name: Grundstück verkaufen
            description:
            - Sobald ein Spieler dein
            - Grundstück gekauft hat,
            - bekommst du die Goldbarren.
        plot_sell_cancel:
            material: BARRIER
            name: Verkauf abbrechen
            description:
            - "Verkaufspreis: %d Goldbarren"
        plot_owner:
            material: STONE_SLAB2
            name: "Besitzer: %s"
            description:
            - Lass dich als
            - Bauhelfer eintragen.
            is_helper:
            - Du bist Bauhelfer
            - und darfst hier
            - mitbauen.
        helpers:
            material: GOLD_HELMET
            name: Bauhelfer
            description:
            - Keine Bauhelfer
            - eingetragen.
            - Klick hier um
            - Bauhelfer ein-
            - oder auszutragen.
        votelinks:
            material: RED_ROSE
            name: Vote Links
            description:
            - Du bekommst
            - 1 Goldbarren
            - als Dankeschön
        warps:
            material: ENDER_PEARL
            name: Warps
            description:
            - Überwinde grosse
            - Entfernungen mit
            - den Warps
    action:
        plot:
            sell:
                release: "\u00A7aDas Grundstück ist für \u00A72%d Goldbarren \u00A7azum Verkauft freigegeben."
                price:
                    input: "\u00A7eWieviel Goldbarren möchtest du für dein Grundstück haben:"
                    error: "\u00A74Mindestens 1 Goldbarren musst du eintragen!"
            sell_cancel:
                success: "\u00A7aGrundstück Verkauft ist zurückgenommen."
                error: "\u00A74Grundstück Verkauft konnte nicht zurück genommen werden!"
            buy:
                success: "\u00A7aJetzt gehört dir das Grundstück. \u00A7fPvP ist hier ausgeschaltet."
                broke: "\u00A74Du hast nicht genug Goldbarren um das Grundstück bezahlen zu können!"
        helper:
            name: "\u00A7eWie heisst der Bauhelfer den du ein oder austragen möchtest:"
            add: "\u00A7aBauhelfer \u00A72%s \u00A7aist willig zum Arbeiten."
            remove: "\u00A7aBauhelfer \u00A72%s \u00A7awurde gekündigt."
            inform_helper: "\u00A7eDu kannst \u00A76%s \u00A7ejetzt beim bauen helfen."
            player_no_exists: "\u00A74Der Spieler \u00A7c%s \u00A74existiert nicht!"
        votelist:
        - "\u00A76***************************************************\n* \u00A7eVote Links\n\u00A76***************************************************"
        - http://www.minecraft-serverlist.net/server/16594
warpsmenu:
    menu_title: Warps Menü
    items:
        respawn:
            name: Hospital
        firstjoin:
            name: Spawn
        bed:
            name: Bett
            error: "\u00A74Du hast dich noch in keinem Bed schlafen gelegt!"
currency: GOLD_INGOT
vote:
    price: 1
    thanks: "\u00A76%s \u00A7edanke fuer dein Voting. Du bekommst \u00A76%d\u00A76 Goldbarren."
cachesize:
    chunklog: 10
    plotprotect: 10
    helper: 10