name: SpigotSurvivalKit
main: de.schillermann.spigotsurvivalkit.Main
version: 1.0
softdepend: [Votifier] 
commands:
    plot:
        usage: /<command> <release>
        description: Gives a Plot free
        permission: spigotsurvivalkit.plot
    bank:
        usage: /<command> <Spieler> [Diamanten]
        description: Displays the Player Balance or transfers money
        permission: spigotsurvivalkit.bank
    warp:
        usage: /<command> <set|remove> <warp name> <description>
        description: Set or remove a warp
        permission: spigotsurvivalkit.warp