name: SpigotSurvivalKit
main: de.schillermann.spigotsurvivalkit.Main
version: 0.4
softdepend: [Votifier] 
commands:
    jail:
        usage: /<command> <player>
        description: Locks a a player in Jail
        permission: spigotsurvivalkit.imprison
    plot:
        usage: /<command> <release>
        description: Gives a Plot free
        permission: spigotsurvivalkit.plot
    bank:
        usage: /<command> <Spieler> [Diamanten]
        description: Displays the Player Balance or transfers money
        permission: spigotsurvivalkit.bank